apiVersion: v1
kind: Pod
metadata:
  name: error-test
spec:
  containers:
  - name: nginx
    image: nginxhdbgnb 
    # ImagePullbackoff(image wrong echinapudu)
  - name: almalinux
    image: almalinux:9
  #   # container lo no run command so it will thrown an error